version: "3.8"

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/database.db:/app/database.db
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - dashboard

  dashboard:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dashboard_app
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=1
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
      - dashboard